name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure gh-pages branch exists
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages || git checkout -b gh-pages
        git merge --allow-unrelated-histories origin/gh-pages

    - name: Copy files from main
      run: |
        rsync -av --exclude=build --exclude=.git ./ /path/to/gh-pages

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Remove unnecessary files
      run: |
        ls | grep -v 'build' | xargs rm -rf

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Build and deploy updates"
        git push origin gh-pages
